package blue.heldplayer.pegen4j.parser.node;

import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Base class for concrete syntax nodes generated by the parser generator.
 */
public abstract non-sealed class RuleContext extends ParseNode {

  private final @NotNull List<@NotNull ParseNode> children = new ArrayList<>();

  @Override
  public @NotNull List<@NotNull ParseNode> children() {
    return Collections.unmodifiableList(this.children);
  }

  /**
   * @hidden For use by the generated parser.
   */
  public void add(@NotNull ParseNode child) {
    this.children.add(child);
  }

}
