package blue.heldplayer.pegen4j.generator;

import blue.heldplayer.pegen4j.unit.AltUnit;
import blue.heldplayer.pegen4j.unit.ConcreteNodeElement;
import blue.heldplayer.pegen4j.unit.GrammarUnit;
import blue.heldplayer.pegen4j.unit.RuleUnit;
import blue.heldplayer.pegen4j.util.StringUtils;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

public final class JavaVisitorGenerator {

  private final GrammarUnit grammarUnit;
  private final String outputClassName;
  private final String outputPackage;
  private final Set<String> outputImportedPackages;

  public JavaVisitorGenerator(JavaParserGenerator parserGenerator) {
    this.grammarUnit = parserGenerator.grammarUnit;
    this.outputClassName = parserGenerator.outputClassName;
    this.outputPackage = parserGenerator.outputPackage;
    this.outputImportedPackages = parserGenerator.outputImportedPackages;
  }

  public Map<String, String> generateFiles() {
    var files = new LinkedHashMap<String, String>();
    var visitorName = this.outputClassName + "Visitor";
    var astBuilderName = this.outputClassName + "AstBuilder";
    files.put(this.outputPackage + "." + visitorName, generateVisitorInterface(visitorName));
    files.put(this.outputPackage + "." + astBuilderName, generateAstBuilder(visitorName, astBuilderName));
    return files;
  }

  private String generateVisitorInterface(String visitorName) {
    var out = new FileGenerator();
    out.line("// generated by Pegen4J");
    out.line("package " + this.outputPackage + ";");
    out.line();
    out.line("import " + this.outputPackage + ".cst.*;");
    out.line();
    out.line("@SuppressWarnings(\"ALL\")");
    out.line("public interface " + visitorName + " {");
    try (var _ = out.withIndentation()) {
      this.grammarUnit.ruleByName.keySet()
        .stream()
        .map(StringUtils::toPascalCase)
        .forEachOrdered(name ->
          out.line("default Object visit" + name + "(" + name + "Context ctx) { visitChildren(ctx); return null; }")
        );
      out.line();
      out.line("default Object visit(" + Constants.QUALIFIED_PARSE_NODE + " node) {");
      try (var _ = out.withIndentation()) {
        out.line("return switch (node) {");
        try (var _ = out.withIndentation()) {
          this.grammarUnit.ruleByName.keySet()
            .stream()
            .map(StringUtils::toPascalCase)
            .forEachOrdered(name ->
              out.line("case " + name + "Context c -> visit" + name + "(c);")
            );
          out.line("default -> null;");
        }
        out.line("};");
      }
      out.line("}");
      out.line();
      out.line("default void visitChildren(" + Constants.QUALIFIED_RULE_CONTEXT + " ctx) {");
      try (var _ = out.withIndentation()) {
        out.line("for (" + Constants.QUALIFIED_PARSE_NODE + " child : ctx.children()) {");
        try (var _ = out.withIndentation()) {
          out.line("if (child instanceof " + Constants.QUALIFIED_RULE_CONTEXT + " rc) {");
          try (var _ = out.withIndentation()) {
            out.line("visit(rc);");
          }
          out.line("}");
        }
        out.line("}");
      }
      out.line("}");
    }
    out.line("}");

    return out.getOutput();
  }

  private String generateAstBuilder(String visitorName, String astBuilderName) {
    var out = new FileGenerator();
    out.line("// generated by Pegen4J");
    out.line("package " + this.outputPackage + ";");
    out.line();
    out.line("import " + Constants.QUALIFIED_PATTERN_TOKEN_NODE + ";");
    out.line("import " + Constants.QUALIFIED_STRING_TOKEN_NODE + ";");
    out.line("import " + this.outputPackage + ".cst.*;");
    for (var pkg : this.outputImportedPackages) {
      out.line("import " + pkg + ";");
    }
    out.line();
    out.line("import java.util.Optional;");
    out.line("import java.util.stream.Collectors;");
    out.line();
    out.line("@SuppressWarnings(\"ALL\")");
    out.line("public class " + astBuilderName + " implements " + visitorName + " {");
    try (var _ = out.withIndentation()) {
      for (RuleUnit rule : this.grammarUnit.ruleByName.values()) {
        generateAstBuilderMethod(out, rule);
      }
    }
    out.line("}");

    return out.getOutput();
  }

  private void generateAstBuilderMethod(FileGenerator out, RuleUnit rule) {
    var name = rule.getName();
    var pascalName = StringUtils.toPascalCase(name);
    var astType = rule.getTypeName();

    out.line("@Override");
    out.line("public " + astType + " visit" + pascalName + "(" + pascalName + "Context λ_ctx) {");
    try (var _ = out.withIndentation()) {
      if (rule.getAlts().size() == 1 && rule.getAlts().getFirst().getLabelName() == null) {
        generateAltBody(out, rule.getAlts().getFirst(), "λ_ctx", "return");
      } else {
        out.line("return switch (λ_ctx) {");
        try (var _ = out.withIndentation()) {
          for (var alt : rule.getAlts()) {
            out.line("case " + alt.getQualifiedContextClassName() + " λ_alt -> {");
            try (var _ = out.withIndentation()) {
              generateAltBody(out, alt, "λ_alt", "yield");
            }
            out.line("}");
          }
        }
        out.line("};");
      }
    }
    out.line("}");
  }

  private void generateAltBody(FileGenerator out, AltUnit alt, String receiver, String returnOrYield) {
    for (var field : alt.getContextFields()) {
      out.line(binding(field, receiver));
    }

    var returnValue = alt.getAction();
    if (returnValue == null) {
      var localNames = alt.getContextFields().stream().map(ConcreteNodeElement::name).toList();
      if (localNames.size() == 1) {
        returnValue = localNames.getFirst();
      } else {
        returnValue = "new Object[]{" + String.join(", ", localNames) + "}";
      }
    }

    out.line(returnOrYield + " " + returnValue + ";");
  }

  private String binding(ConcreteNodeElement f, String receiver) {
    var accessor = receiver + "." + f.name();
    if (f.terminal()) {
      return "var " + f.name() + " = " + accessor + ";";
    }
    var referencedName = f.ref();
    assert referencedName != null : "non-terminals should always have a name set";

    var ruleUnit = this.grammarUnit.ruleByName.get(referencedName);
    var ruleType = ruleUnit != null ? ruleUnit.getTypeName() : "Object";
    var visitorCall = ruleUnit != null
      ? "visit" + StringUtils.toPascalCase(ruleUnit.getName())
      : "(" + ruleType + ") visit";

    return "var " + f.name() + " = " + switch (f.shape()) {
      case SCALAR -> visitorCall + "(" + accessor + ");";
      case OPT -> "Optional.ofNullable(" + accessor + ").map(c -> " + visitorCall + "(c)).orElse(null);";
      case LIST -> accessor + ".stream().map(c -> " + visitorCall + "(c)).collect(Collectors.toList());";
    };
  }

}
