package blue.heldplayer.pegen4j.generator;

import blue.heldplayer.pegen4j.peg.ast.Item;
import blue.heldplayer.pegen4j.unit.AltUnit;
import blue.heldplayer.pegen4j.unit.GrammarUnit;
import blue.heldplayer.pegen4j.unit.ItemUnit;
import blue.heldplayer.pegen4j.unit.RuleUnit;
import blue.heldplayer.pegen4j.util.StringUtils;

import java.util.*;

public final class JavaParserGenerator {

  private record AtomCall(String expr, String type) {
  }

  final GrammarUnit grammarUnit;
  final String outputClassName;
  final String outputPackage;
  final Set<String> outputImportedPackages;

  public JavaParserGenerator(GrammarUnit grammarUnit) {
    this.grammarUnit = grammarUnit;

    if (grammarUnit.hasErrors()) {
      throw new IllegalArgumentException("Grammar unit contains errors");
    }

    if (!this.grammarUnit.optionValuesByName.containsKey(Constants.OPTION_JAVA_CLASS_NAME)) {
      throw new GrammarException("Missing required option " + Constants.OPTION_JAVA_CLASS_NAME);
    } else {
      var values = this.grammarUnit.optionValuesByName.get(Constants.OPTION_JAVA_CLASS_NAME);
      if (values.size() > 1) {
        throw new GrammarException("Option " + Constants.OPTION_JAVA_CLASS_NAME + " can only be provided once");
      }
      this.outputClassName = values.getFirst();
    }
    if (!this.grammarUnit.optionValuesByName.containsKey(Constants.OPTION_JAVA_PACKAGE)) {
      this.outputPackage = null;
    } else {
      var values = this.grammarUnit.optionValuesByName.get(Constants.OPTION_JAVA_PACKAGE);
      if (values.size() > 1) {
        throw new GrammarException("Option " + Constants.OPTION_JAVA_PACKAGE + " can only be provided once");
      }
      this.outputPackage = values.getFirst();
    }

    this.outputImportedPackages = Set.copyOf(this.grammarUnit.optionValuesByName.getOrDefault(Constants.OPTION_JAVA_IMPORT, List.of()));
  }

  public Map<String, String> generateFiles() {
    var files = new LinkedHashMap<String, String>();

    files.put((this.outputPackage != null ? this.outputPackage + "." : "") + this.outputClassName, this.generateParserClassFile());

    for (RuleUnit rule : this.grammarUnit.ruleByName.values()) {
      files.put((this.outputPackage != null ? this.outputPackage + "." : "") + "cst." + rule.getContextClassName(), generateContextClassFile(rule, this.outputPackage));
    }
    return files;
  }

  private String generateParserClassFile() {
    var out = new FileGenerator();
    out.line("// generated by Pegen4J");
    if (this.outputPackage != null) {
      out.line("package " + this.outputPackage + ";");
      out.line();
      out.line("import " + this.outputPackage + ".cst.*;");
    } else {
      out.line("import cst.*;");
    }
    out.line();
    out.line("import blue.heldplayer.pegen4j.parser.AbstractParser;");
    out.line("import blue.heldplayer.pegen4j.parser.TokenType;");
    out.line("import " + Constants.QUALIFIED_PATTERN_TOKEN_NODE + ";");
    out.line("import " + Constants.QUALIFIED_STRING_TOKEN_NODE + ";");
    out.line();
    out.line("import java.net.URI;");
    out.line("import java.util.ArrayList;");
    out.line();
    out.line("@SuppressWarnings(\"ALL\")");
    out.line("public class " + this.outputClassName + " extends AbstractParser {");
    try (var _ = out.withIndentation()) {
      generateConstructor(out);
      for (RuleUnit rule : this.grammarUnit.ruleByName.values()) {
        out.line();
        generateRuleParser(out, rule);
      }
      out.line();
    }
    out.line("}");

    return out.getOutput();
  }

  private void generateConstructor(FileGenerator out) {
    var tokenNames = new ArrayList<String>();
    var ignoredTokenNames = new ArrayList<String>();
    for (var entry : this.grammarUnit.tokenPatternByName.entrySet()) {
      var name = entry.getKey();

      out.line(
        "public static final TokenType " + name + " = new TokenType("
          + StringUtils.toJavaString(name) + ", "
          + StringUtils.toJavaString(entry.getValue())
          + ");"
      );
      if (this.grammarUnit.ignoredTokenNames.contains(name)) {
        ignoredTokenNames.add(name);
      } else {
        tokenNames.add(name);
      }
    }

    out.line();
    out.line("public static final TokenType[] TOKENS = new TokenType[]{" + String.join(", ", tokenNames) + "};");
    out.line("public static final TokenType[] IGNORED_TOKENS = new TokenType[]{" + String.join(", ", ignoredTokenNames) + "};");
    out.line("public static final String[] KEYWORDS = new String[]{" + StringUtils.toJavaStringList(this.grammarUnit.keywords) + "};");
    out.line("public static final String[] SOFT_KEYWORDS = new String[]{" + StringUtils.toJavaStringList(this.grammarUnit.softKeywords) + "};");
    if (this.grammarUnit.recoveryEnabled()) {
      out.line("public static final String[] SYNC_TOKENS = new String[]{" + StringUtils.toJavaStringList(this.grammarUnit.recoverTokens) + "};");
    }
    out.line();
    out.line("public " + this.outputClassName + "(URI sourceUri, CharSequence sourceString) {");
    try (var _ = out.withIndentation()) {
      out.line("super(sourceUri, sourceString, TOKENS, IGNORED_TOKENS, KEYWORDS, SOFT_KEYWORDS);");
    }
    out.line("}");
  }

  private void generateRuleParser(FileGenerator out, RuleUnit rule) {
    var name = rule.getName();
    var ctxType = rule.getContextClassName();
    boolean leftRecursive = this.grammarUnit.leftRecursiveRules.contains(name);
    boolean leader = this.grammarUnit.leadingRules.contains(name);
    String memo = leftRecursive ? (leader ? "memoizedLeftRecursive" : "logged") : "memoized";

    out.line("public " + ctxType + " " + name + "() {");
    try (var _ = out.withIndentation()) {
      out.line("return super." + memo + "(\"" + name + "\", () -> {");
      try (var _ = out.withIndentation()) {
        out.line("var λ_mark = super.mark();");
        if (rule.hasCut()) {
          out.line("var λ_cut = false;");
        }
        var altsAlwaysReturn = false;
        for (AltUnit alt : rule.getAlts()) {
          generateAltParser(out, alt);
          if (alt.alwaysReturns()) {
            altsAlwaysReturn = true;
            break;
          }
        }
        if (!altsAlwaysReturn) {
          out.line("return null;");
        } else {
          out.line("// unreachable");
        }
      }
      out.line("});");
    }
    out.line("}");
  }

  private void generateAltParser(FileGenerator out, AltUnit alt) {
    out.line("// " + alt.getNode().describe());
    out.line("do {");
    try (var _ = out.withIndentation()) {
      out.line("var λ_ctx = new " + alt.getQualifiedContextClassName() + "();");
      for (var item : alt.getItems()) {
        generateItem(out, item);
      }
      out.line("super.finish(λ_ctx, λ_mark);");
      out.line("return λ_ctx;");
    }
    out.line("} while (false);");
    if (alt.alwaysReturns()) {
      return;
    }
    // While a recovery is pending, do not backtrack: the synchronized position
    // must propagate up to the enclosing repetition that will consume it.
    if (this.grammarUnit.recoveryEnabled()) {
      out.line("if (!super.pendingRecovery) super.reset(λ_mark);");
    } else {
      out.line("super.reset(λ_mark);");
    }
    if (alt.hasCut()) {
      if (this.grammarUnit.recoveryEnabled()) {
        // Committed then failed: panic-mode recover (record + synchronize), then
        // report failure so the enclosing repetition keeps iterating.
        out.line("if (λ_cut) { super.recover(SYNC_TOKENS); return null; }");
      } else {
        out.line("if (λ_cut) return null;");
      }
    }
  }

  private void generateItem(FileGenerator out, ItemUnit unit) {
    var target = unit.item().target();

    switch (target) {
      case Item.Cut _ -> out.line("λ_cut = true;");
      case Item.EofMarker _ -> out.line("if (!super.expectEof()) break;");
      case Item.PositiveLookahead la -> generateLookahead(out, atomCall(la.item), true);
      case Item.NegativeLookahead la -> generateLookahead(out, atomCall(la.item), false);
      case Item.NameLeaf leaf -> generateRequiredValue(out, unit.assertField().name(), atomCall(leaf));
      case Item.StringLeaf leaf -> {
        var atom = atomCall(leaf);
        var field = unit.field();
        if (field == null) {
          out.line("if (" + atom.expr() + " == null) break;");
        } else {
          generateRequiredValue(out, field.name(), atom);
        }
      }
      case Item.Repeat0 repeat -> generateLoop(out, repeat.item, unit.assertField().name(), false);
      case Item.Repeat1 repeat -> generateLoop(out, repeat.item, unit.assertField().name(), true);
      case Item.Gather gather -> generateGather(out, gather.separator, gather.item, unit.assertField().name());
      case Item.Opt opt -> generateOpt(out, opt.item, unit.assertField().name());
      case Item.Forced _ -> throw new GrammarException("forced (&&) is not yet supported");
      default -> throw new GrammarException("unsupported item: " + target.getClass().getSimpleName());
    }
  }

  private void generateRequiredValue(FileGenerator out, String fieldName, AtomCall atom) {
    var local = "λv_" + fieldName;
    out.line("var " + local + " = " + atom.expr() + ";");
    out.line("if (" + local + " == null) break;");
    out.line("λ_ctx." + fieldName + " = " + local + ";");
    out.line("λ_ctx.add(" + local + ");");
  }

  private void generateLoop(FileGenerator out, Item element, String fieldName, boolean loop1) {
    var atom = atomCall(element);
    var list = "λv_" + fieldName;
    var elem = "λe_" + fieldName;
    out.line("var " + list + " = new ArrayList<" + atom.type() + ">();");
    out.line("while (true) {");
    try (var _ = out.withIndentation()) {
      out.line("var λ_m = super.mark();");
      out.line("var " + elem + " = " + atom.expr() + ";");
      if (this.grammarUnit.recoveryEnabled()) {
        out.line("if (" + elem + " == null) {");
        try (var _ = out.withIndentation()) {
          out.line("if (super.pendingRecovery) { super.pendingRecovery = false; continue; }");
          out.line("super.reset(λ_m);");
          out.line("break;");
        }
        out.line("}");
      } else {
        out.line("if (" + elem + " == null) { super.reset(λ_m); break; }");
      }
      out.line(list + ".add(" + elem + ");");
      out.line("λ_ctx.add(" + elem + ");");
    }
    out.line("}");
    if (loop1) {
      out.line("if (" + list + ".isEmpty()) break;");
    }
    out.line("λ_ctx." + fieldName + " = " + list + ";");
  }

  private void generateGather(FileGenerator out, Item separator, Item element, String fieldName) {
    var atom = atomCall(element);
    var sep = atomCall(separator);
    var list = "λv_" + fieldName;
    var first = "λf_" + fieldName;
    var elem = "λe_" + fieldName;
    var sepVar = "λs_" + fieldName;
    out.line("var " + list + " = new ArrayList<" + atom.type() + ">();");
    out.line("var " + first + " = " + atom.expr() + ";");
    out.line("if (" + first + " == null) break;");
    out.line(list + ".add(" + first + ");");
    out.line("λ_ctx.add(" + first + ");");
    out.line("while (true) {");
    try (var _ = out.withIndentation()) {
      out.line("var λ_m = super.mark();");
      out.line("var " + sepVar + " = " + sep.expr() + ";");
      out.line("if (" + sepVar + " == null) { super.reset(λ_m); break; }");
      out.line("var " + elem + " = " + atom.expr() + ";");
      if (this.grammarUnit.recoveryEnabled()) {
        out.line("if (" + elem + " == null) {");
        try (var _ = out.withIndentation()) {
          out.line("if (super.pendingRecovery) { super.pendingRecovery = false; continue; }");
          out.line("super.reset(λ_m);");
          out.line("break;");
        }
        out.line("}");
      } else {
        out.line("if (" + elem + " == null) { super.reset(λ_m); break; }");
      }
      out.line(list + ".add(" + elem + ");");
      out.line("λ_ctx.add(" + elem + ");");
    }
    out.line("}");
    out.line("λ_ctx." + fieldName + " = " + list + ";");
  }

  private void generateOpt(FileGenerator out, Item inner, String fieldName) {
    var atom = atomCall(inner);
    var local = "λv_" + fieldName;
    out.line("var " + local + " = " + atom.expr() + ";");
    out.line("if (" + local + " != null) λ_ctx.add(" + local + ");");
    out.line("λ_ctx." + fieldName + " = " + local + ";");
  }

  private void generateLookahead(FileGenerator out, AtomCall atom, boolean positive) {
    out.line("{");
    try (var _ = out.withIndentation()) {
      out.line("var λ_lookaheadMark = super.mark();");
      out.line("boolean λ_ok = (" + atom.expr() + " != null);");
      out.line("super.reset(λ_lookaheadMark);");
      String text = positive ? "if (!λ_ok) break;" : "if (λ_ok) break;";
      out.line(text);
    }
    out.line("}");
  }

  private AtomCall atomCall(Item item) {
    if (item instanceof Item.Named named) {
      return atomCall(named.item);
    }
    var info = this.grammarUnit.classifyAtom(item);
    var expr = switch (item) {
      case Item.NameLeaf leaf -> {
        var name = leaf.name.string();
        if (this.grammarUnit.tokenPatternByName.containsKey(name)) {
          yield "super.expect(" + this.outputClassName + "." + name + ")";
        } else if (this.grammarUnit.ruleByName.containsKey(name)) {
          yield "this." + name + "()";
        }
        yield "null"; // fallback
      }
      case Item.StringLeaf leaf -> "super.expect(" + StringUtils.toJavaString(leaf.string.unquoted()) + ")";
      default -> throw new GrammarException("unexpected item: " + item);
    };
    return new AtomCall(expr, info.type());
  }

  private static String generateContextClassFile(RuleUnit rule, String outputPackage) {
    var rootClassName = rule.getContextClassName();

    var out = new FileGenerator();
    out.line("// generated by Pegen4J");
    out.line("package " + outputPackage + ".cst;");
    out.line();
    generateContextClassImports(out, rule);

    out.line("@SuppressWarnings(\"ALL\")");
    if (rule.getAlts().size() == 1 && rule.getAlts().getFirst().getLabelName() == null) {
      out.line("public final class " + rootClassName + " extends " + Constants.QUALIFIED_RULE_CONTEXT + " {");
      try (var _ = out.withIndentation()) {
        generateContextClassContents(out, rule.getAlts().getFirst());
      }
      out.line("}");
    } else {
      out.line("public sealed abstract class " + rootClassName + " extends " + Constants.QUALIFIED_RULE_CONTEXT + " {");
      try (var _ = out.withIndentation()) {
        for (var alt : rule.getAlts()) {
          out.line();
          out.line("public static final class " + alt.getSimpleContextClassName() + " extends " + rootClassName + " {");
          try (var _ = out.withIndentation()) {
            generateContextClassContents(out, alt);
          }
          out.line("}");
        }
      }
      out.line("}");
    }
    return out.getOutput();
  }

  private static void generateContextClassImports(FileGenerator out, RuleUnit rule) {
    var importedPackages = new TreeSet<String>();
    for (var alt : rule.getAlts()) {
      for (var f : alt.getContextFields()) {
        var type = f.type();
        if (type.startsWith("List<")) {
          importedPackages.add("java.util.List");
        }
        if (type.contains("PatternTokenNode")) {
          importedPackages.add(Constants.QUALIFIED_PATTERN_TOKEN_NODE);
        }
        if (type.contains("StringTokenNode")) {
          importedPackages.add(Constants.QUALIFIED_STRING_TOKEN_NODE);
        }
        if (type.contains("ParseNode")) {
          importedPackages.add(Constants.QUALIFIED_PARSE_NODE);
        }
      }
    }
    if (!importedPackages.isEmpty()) {
      for (var packageName : importedPackages) {
        out.line("import " + packageName + ";");
      }
      out.line();
    }
  }

  private static void generateContextClassContents(FileGenerator out, AltUnit alt) {
    var fields = alt.getContextFields();
    if (!fields.isEmpty()) {
      for (var f : fields) {
        out.line("public " + f.type() + " " + f.name() + ";");
      }
    }
  }

}
