// generated by Pegen4J
package blue.heldplayer.pegen4j.peg;

import blue.heldplayer.pegen4j.peg.cst.*;

import blue.heldplayer.pegen4j.parser.AbstractParser;
import blue.heldplayer.pegen4j.parser.TokenType;
import blue.heldplayer.pegen4j.parser.node.PatternTokenNode;
import blue.heldplayer.pegen4j.parser.node.StringTokenNode;

import java.net.URI;
import java.util.ArrayList;

@SuppressWarnings("ALL")
public class Pegen4JParser extends AbstractParser {
  public static final TokenType NAME = new TokenType("NAME", "(?i)[a-z_][a-z0-9_]*", false);
  public static final TokenType STRING = new TokenType("STRING", "'(?:[^'\\n\\r\\\\]|\\\\[tbnrf'\"\\\\])+'|\"(?:[^\"\\n\\r\\\\]|\\\\[tbnrf'\"\\\\])+\"", false);
  public static final TokenType PATTERN = new TokenType("PATTERN", "\\/((?:[^\\r\\n\\[/\\\\]|\\\\.|\\[(?:[^\\r\\n\\]\\\\]|\\\\.)*\\])+)\\/", false);
  public static final TokenType TYPE = new TokenType("TYPE", "\\[[^\\[\\]]*\\]", false);
  public static final TokenType ACTION = new TokenType("ACTION", "\\{[^{}]*\\}", false);
  public static final TokenType WS = new TokenType("WS", "\\s+", false);
  public static final TokenType COMMENT = new TokenType("COMMENT", "\\/\\/.*?(?:\\n|$)", false);

  public static final TokenType[] TOKENS = new TokenType[]{NAME, STRING, PATTERN, TYPE, ACTION};
  public static final TokenType[] IGNORED_TOKENS = new TokenType[]{WS, COMMENT};
  public static final String[] KEYWORDS = new String[]{};
  public static final String[] SOFT_KEYWORDS = new String[]{"store_location"};
  public static final String[] SYNC_TOKENS = new String[]{";"};

  public Pegen4JParser(URI sourceUri, CharSequence sourceString) {
    super(sourceUri, sourceString, TOKENS, IGNORED_TOKENS, KEYWORDS, SOFT_KEYWORDS, false);
  }

  public GrammarUnitContext grammar_unit() {
    return super.memoized("grammar_unit", () -> {
      var λ_mark = super.mark();
      // grammar_elements=grammar_element* $ { new Grammar(grammar_elements) }
      do {
        var λ_ctx = new GrammarUnitContext();
        var λv_grammar_elements = new ArrayList<GrammarElementContext>();
        while (true) {
          var λ_m = super.mark();
          var λe_grammar_elements = this.grammar_element();
          if (λe_grammar_elements == null) {
            if (super.pendingRecovery) { super.pendingRecovery = false; continue; }
            super.reset(λ_m);
            break;
          }
          λv_grammar_elements.add(λe_grammar_elements);
          λ_ctx.add(λe_grammar_elements);
        }
        λ_ctx.grammar_elements = λv_grammar_elements;
        if (!super.expectEof()) break;
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      return null;
    });
  }

  public GrammarElementContext grammar_element() {
    return super.memoized("grammar_element", () -> {
      var λ_mark = super.mark();
      // meta
      do {
        var λ_ctx = new GrammarElementContext.Alt1();
        var λv_meta = this.meta();
        if (λv_meta == null) break;
        λ_ctx.meta = λv_meta;
        λ_ctx.add(λv_meta);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      // token
      do {
        var λ_ctx = new GrammarElementContext.Alt2();
        var λv_token = this.token();
        if (λv_token == null) break;
        λ_ctx.token = λv_token;
        λ_ctx.add(λv_token);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      // rule
      do {
        var λ_ctx = new GrammarElementContext.Alt3();
        var λv_rule = this.rule();
        if (λv_rule == null) break;
        λ_ctx.rule = λv_rule;
        λ_ctx.add(λv_rule);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      return null;
    });
  }

  public MetaContext meta() {
    return super.memoized("meta", () -> {
      var λ_mark = super.mark();
      // '@keyword' STRING { new Meta.Keyword(STRING) }
      do {
        var λ_ctx = new MetaContext.Keyword();
        if (super.expect("@keyword") == null) break;
        var λv_STRING = super.expect(Pegen4JParser.STRING);
        if (λv_STRING == null) break;
        λ_ctx.STRING = λv_STRING;
        λ_ctx.add(λv_STRING);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      // '@ignore' NAME { new Meta.Ignore(NAME) }
      do {
        var λ_ctx = new MetaContext.Ignore();
        if (super.expect("@ignore") == null) break;
        var λv_NAME = super.expect(Pegen4JParser.NAME);
        if (λv_NAME == null) break;
        λ_ctx.NAME = λv_NAME;
        λ_ctx.add(λv_NAME);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      // '@option' NAME STRING { new Meta.Option(NAME, STRING) }
      do {
        var λ_ctx = new MetaContext.Option();
        if (super.expect("@option") == null) break;
        var λv_NAME = super.expect(Pegen4JParser.NAME);
        if (λv_NAME == null) break;
        λ_ctx.NAME = λv_NAME;
        λ_ctx.add(λv_NAME);
        var λv_STRING = super.expect(Pegen4JParser.STRING);
        if (λv_STRING == null) break;
        λ_ctx.STRING = λv_STRING;
        λ_ctx.add(λv_STRING);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      // '@recover' tokens=STRING+ { new Meta.Recover(tokens) }
      do {
        var λ_ctx = new MetaContext.Recover();
        if (super.expect("@recover") == null) break;
        var λv_tokens = new ArrayList<PatternTokenNode>();
        while (true) {
          var λ_m = super.mark();
          var λe_tokens = super.expect(Pegen4JParser.STRING);
          if (λe_tokens == null) {
            if (super.pendingRecovery) { super.pendingRecovery = false; continue; }
            super.reset(λ_m);
            break;
          }
          λv_tokens.add(λe_tokens);
          λ_ctx.add(λe_tokens);
        }
        if (λv_tokens.isEmpty()) break;
        λ_ctx.tokens = λv_tokens;
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      return null;
    });
  }

  public TokenContext token() {
    return super.memoized("token", () -> {
      var λ_mark = super.mark();
      // NAME ':' PATTERN { new TokenDefinition(NAME, PATTERN) }
      do {
        var λ_ctx = new TokenContext();
        var λv_NAME = super.expect(Pegen4JParser.NAME);
        if (λv_NAME == null) break;
        λ_ctx.NAME = λv_NAME;
        λ_ctx.add(λv_NAME);
        if (super.expect(":") == null) break;
        var λv_PATTERN = super.expect(Pegen4JParser.PATTERN);
        if (λv_PATTERN == null) break;
        λ_ctx.PATTERN = λv_PATTERN;
        λ_ctx.add(λv_PATTERN);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      return null;
    });
  }

  public RuleContext rule() {
    return super.memoized("rule", () -> {
      var λ_mark = super.mark();
      var λ_cut = false;
      // NAME TYPE? flags=rule_flag* ':' ~ alts='|'.alt+ ';' { new RuleDefinition(NAME, flags, alts, TYPE) }
      do {
        var λ_ctx = new RuleContext();
        var λv_NAME = super.expect(Pegen4JParser.NAME);
        if (λv_NAME == null) break;
        λ_ctx.NAME = λv_NAME;
        λ_ctx.add(λv_NAME);
        var λv_TYPE = super.expect(Pegen4JParser.TYPE);
        if (λv_TYPE != null) λ_ctx.add(λv_TYPE);
        λ_ctx.TYPE = λv_TYPE;
        var λv_flags = new ArrayList<RuleFlagContext>();
        while (true) {
          var λ_m = super.mark();
          var λe_flags = this.rule_flag();
          if (λe_flags == null) {
            if (super.pendingRecovery) { super.pendingRecovery = false; continue; }
            super.reset(λ_m);
            break;
          }
          λv_flags.add(λe_flags);
          λ_ctx.add(λe_flags);
        }
        λ_ctx.flags = λv_flags;
        if (super.expect(":") == null) break;
        λ_cut = true;
        var λv_alts = new ArrayList<AltContext>();
        var λf_alts = this.alt();
        if (λf_alts == null) break;
        λv_alts.add(λf_alts);
        λ_ctx.add(λf_alts);
        while (true) {
          var λ_m = super.mark();
          var λs_alts = super.expect("|");
          if (λs_alts == null) { super.reset(λ_m); break; }
          var λe_alts = this.alt();
          if (λe_alts == null) {
            if (super.pendingRecovery) { super.pendingRecovery = false; continue; }
            super.reset(λ_m);
            break;
          }
          λv_alts.add(λe_alts);
          λ_ctx.add(λe_alts);
        }
        λ_ctx.alts = λv_alts;
        if (super.expect(";") == null) break;
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      if (λ_cut) { super.recover(SYNC_TOKENS); return null; }
      return null;
    });
  }

  public RuleFlagContext rule_flag() {
    return super.memoized("rule_flag", () -> {
      var λ_mark = super.mark();
      // '#' "store_location" { RuleFlag.STORE_LOCATION }
      do {
        var λ_ctx = new RuleFlagContext();
        if (super.expect("#") == null) break;
        if (super.expect("store_location") == null) break;
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      return null;
    });
  }

  public AltContext alt() {
    return super.memoized("alt", () -> {
      var λ_mark = super.mark();
      // items=named_item+ action? context_name? { new Alt(items, action, context_name) }
      do {
        var λ_ctx = new AltContext();
        var λv_items = new ArrayList<NamedItemContext>();
        while (true) {
          var λ_m = super.mark();
          var λe_items = this.named_item();
          if (λe_items == null) {
            if (super.pendingRecovery) { super.pendingRecovery = false; continue; }
            super.reset(λ_m);
            break;
          }
          λv_items.add(λe_items);
          λ_ctx.add(λe_items);
        }
        if (λv_items.isEmpty()) break;
        λ_ctx.items = λv_items;
        var λv_action = this.action();
        if (λv_action != null) λ_ctx.add(λv_action);
        λ_ctx.action = λv_action;
        var λv_context_name = this.context_name();
        if (λv_context_name != null) λ_ctx.add(λv_context_name);
        λ_ctx.context_name = λv_context_name;
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      return null;
    });
  }

  public ActionContext action() {
    return super.memoized("action", () -> {
      var λ_mark = super.mark();
      // ACTION
      do {
        var λ_ctx = new ActionContext();
        var λv_ACTION = super.expect(Pegen4JParser.ACTION);
        if (λv_ACTION == null) break;
        λ_ctx.ACTION = λv_ACTION;
        λ_ctx.add(λv_ACTION);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      return null;
    });
  }

  public ContextNameContext context_name() {
    return super.memoized("context_name", () -> {
      var λ_mark = super.mark();
      // '#' NAME
      do {
        var λ_ctx = new ContextNameContext();
        if (super.expect("#") == null) break;
        var λv_NAME = super.expect(Pegen4JParser.NAME);
        if (λv_NAME == null) break;
        λ_ctx.NAME = λv_NAME;
        λ_ctx.add(λv_NAME);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      return null;
    });
  }

  public NamedItemContext named_item() {
    return super.memoized("named_item", () -> {
      var λ_mark = super.mark();
      var λ_cut = false;
      // NAME '=' ~ item { new Item.Named(NAME, item) }
      do {
        var λ_ctx = new NamedItemContext.Named();
        var λv_NAME = super.expect(Pegen4JParser.NAME);
        if (λv_NAME == null) break;
        λ_ctx.NAME = λv_NAME;
        λ_ctx.add(λv_NAME);
        if (super.expect("=") == null) break;
        λ_cut = true;
        var λv_item = this.item();
        if (λv_item == null) break;
        λ_ctx.item = λv_item;
        λ_ctx.add(λv_item);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      if (λ_cut) { super.recover(SYNC_TOKENS); return null; }
      // item
      do {
        var λ_ctx = new NamedItemContext.Unnamed();
        var λv_item = this.item();
        if (λv_item == null) break;
        λ_ctx.item = λv_item;
        λ_ctx.add(λv_item);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      // '&' '&' ~ atom { new Item.Forced(atom) }
      do {
        var λ_ctx = new NamedItemContext.Forced();
        if (super.expect("&") == null) break;
        if (super.expect("&") == null) break;
        λ_cut = true;
        var λv_atom = this.atom();
        if (λv_atom == null) break;
        λ_ctx.atom = λv_atom;
        λ_ctx.add(λv_atom);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      if (λ_cut) { super.recover(SYNC_TOKENS); return null; }
      // '&' ~ atom { new Item.PositiveLookahead(atom) }
      do {
        var λ_ctx = new NamedItemContext.PositiveLookahead();
        if (super.expect("&") == null) break;
        λ_cut = true;
        var λv_atom = this.atom();
        if (λv_atom == null) break;
        λ_ctx.atom = λv_atom;
        λ_ctx.add(λv_atom);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      if (λ_cut) { super.recover(SYNC_TOKENS); return null; }
      // '!' ~ atom { new Item.NegativeLookahead(atom) }
      do {
        var λ_ctx = new NamedItemContext.NegativeLookahead();
        if (super.expect("!") == null) break;
        λ_cut = true;
        var λv_atom = this.atom();
        if (λv_atom == null) break;
        λ_ctx.atom = λv_atom;
        λ_ctx.add(λv_atom);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      if (λ_cut) { super.recover(SYNC_TOKENS); return null; }
      // '~' { new Item.Cut() }
      do {
        var λ_ctx = new NamedItemContext.Cut();
        if (super.expect("~") == null) break;
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      // '$' { new Item.EofMarker() }
      do {
        var λ_ctx = new NamedItemContext.Eof();
        if (super.expect("$") == null) break;
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      return null;
    });
  }

  public ItemContext item() {
    return super.memoized("item", () -> {
      var λ_mark = super.mark();
      // atom '?' { new Item.Opt(atom) }
      do {
        var λ_ctx = new ItemContext.Opt();
        var λv_atom = this.atom();
        if (λv_atom == null) break;
        λ_ctx.atom = λv_atom;
        λ_ctx.add(λv_atom);
        if (super.expect("?") == null) break;
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      // atom '*' { new Item.Repeat0(atom) }
      do {
        var λ_ctx = new ItemContext.Repeat0();
        var λv_atom = this.atom();
        if (λv_atom == null) break;
        λ_ctx.atom = λv_atom;
        λ_ctx.add(λv_atom);
        if (super.expect("*") == null) break;
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      // atom '+' { new Item.Repeat1(atom) }
      do {
        var λ_ctx = new ItemContext.Repeat1();
        var λv_atom = this.atom();
        if (λv_atom == null) break;
        λ_ctx.atom = λv_atom;
        λ_ctx.add(λv_atom);
        if (super.expect("+") == null) break;
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      // sep=atom '.' node=atom '+' { new Item.Gather(node, sep) }
      do {
        var λ_ctx = new ItemContext.Gather();
        var λv_sep = this.atom();
        if (λv_sep == null) break;
        λ_ctx.sep = λv_sep;
        λ_ctx.add(λv_sep);
        if (super.expect(".") == null) break;
        var λv_node = this.atom();
        if (λv_node == null) break;
        λ_ctx.node = λv_node;
        λ_ctx.add(λv_node);
        if (super.expect("+") == null) break;
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      // atom
      do {
        var λ_ctx = new ItemContext.Atom();
        var λv_atom = this.atom();
        if (λv_atom == null) break;
        λ_ctx.atom = λv_atom;
        λ_ctx.add(λv_atom);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      return null;
    });
  }

  public AtomContext atom() {
    return super.memoized("atom", () -> {
      var λ_mark = super.mark();
      // NAME { new Item.NameLeaf(NAME) }
      do {
        var λ_ctx = new AtomContext.Name();
        var λv_NAME = super.expect(Pegen4JParser.NAME);
        if (λv_NAME == null) break;
        λ_ctx.NAME = λv_NAME;
        λ_ctx.add(λv_NAME);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      // STRING { new Item.StringLeaf(STRING) }
      do {
        var λ_ctx = new AtomContext.String();
        var λv_STRING = super.expect(Pegen4JParser.STRING);
        if (λv_STRING == null) break;
        λ_ctx.STRING = λv_STRING;
        λ_ctx.add(λv_STRING);
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      if (!super.pendingRecovery) super.reset(λ_mark);
      return null;
    });
  }

}
