// generated by Pegen4J
package blue.heldplayer.pegen4j.peg;

import blue.heldplayer.pegen4j.peg.cst.*;
import blue.heldplayer.pegen4j.peg.ast.*;

import blue.heldplayer.pegen4j.parser.node.PatternTokenNode;
import blue.heldplayer.pegen4j.parser.node.StringTokenNode;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@SuppressWarnings("ALL")
public class Pegen4JParserAstBuilder implements Pegen4JParserVisitor {
  @Override
  public Grammar visitGrammarUnit(GrammarUnitContext λ_ctx) {
    var grammar_elements = λ_ctx.grammar_elements.stream().map(c -> visitGrammarElement(c)).collect(Collectors.toList());
    return new Grammar(grammar_elements);
  }
  @Override
  public GrammarElement visitGrammarElement(GrammarElementContext λ_ctx) {
    return switch (λ_ctx) {
      case GrammarElementContext.Alt1 λ_alt -> {
        var meta = visitMeta(λ_alt.meta);
        yield meta;
      }
      case GrammarElementContext.Alt2 λ_alt -> {
        var token = visitToken(λ_alt.token);
        yield token;
      }
      case GrammarElementContext.Alt3 λ_alt -> {
        var rule = visitRule(λ_alt.rule);
        yield rule;
      }
    };
  }
  @Override
  public Meta visitMeta(MetaContext λ_ctx) {
    return switch (λ_ctx) {
      case MetaContext.Keyword λ_alt -> {
        var STRING = λ_alt.STRING;
        yield new Meta.Keyword(STRING);
      }
      case MetaContext.Ignore λ_alt -> {
        var NAME = λ_alt.NAME;
        yield new Meta.Ignore(NAME);
      }
      case MetaContext.Option λ_alt -> {
        var NAME = λ_alt.NAME;
        var STRING = λ_alt.STRING;
        yield new Meta.Option(NAME, STRING);
      }
      case MetaContext.Recover λ_alt -> {
        var tokens = λ_alt.tokens;
        yield new Meta.Recover(tokens);
      }
    };
  }
  @Override
  public TokenDefinition visitToken(TokenContext λ_ctx) {
    var NAME = λ_ctx.NAME;
    var PATTERN = λ_ctx.PATTERN;
    return new TokenDefinition(NAME, PATTERN);
  }
  @Override
  public RuleDefinition visitRule(RuleContext λ_ctx) {
    return switch (λ_ctx) {
      case RuleContext.Typed λ_alt -> {
        var NAME = λ_alt.NAME;
        var TYPE = λ_alt.TYPE;
        var alts = λ_alt.alts.stream().map(c -> visitAlt(c)).collect(Collectors.toList());
        yield new RuleDefinition(NAME, alts, TYPE);
      }
      case RuleContext.Untyped λ_alt -> {
        var NAME = λ_alt.NAME;
        var alts = λ_alt.alts.stream().map(c -> visitAlt(c)).collect(Collectors.toList());
        yield new RuleDefinition(NAME, alts, null);
      }
    };
  }
  @Override
  public Alt visitAlt(AltContext λ_ctx) {
    var items = λ_ctx.items.stream().map(c -> visitNamedItem(c)).collect(Collectors.toList());
    var action = Optional.ofNullable(λ_ctx.action).map(c -> visitAction(c)).orElse(null);
    var context_name = Optional.ofNullable(λ_ctx.context_name).map(c -> visitContextName(c)).orElse(null);
    return new Alt(items, action, context_name);
  }
  @Override
  public PatternTokenNode visitAction(ActionContext λ_ctx) {
    var ACTION = λ_ctx.ACTION;
    return ACTION;
  }
  @Override
  public PatternTokenNode visitContextName(ContextNameContext λ_ctx) {
    var NAME = λ_ctx.NAME;
    return NAME;
  }
  @Override
  public Item visitNamedItem(NamedItemContext λ_ctx) {
    return switch (λ_ctx) {
      case NamedItemContext.Named λ_alt -> {
        var NAME = λ_alt.NAME;
        var item = visitItem(λ_alt.item);
        yield new Item.Named(NAME, item);
      }
      case NamedItemContext.Unnamed λ_alt -> {
        var item = visitItem(λ_alt.item);
        yield item;
      }
      case NamedItemContext.Forced λ_alt -> {
        var atom = visitAtom(λ_alt.atom);
        yield new Item.Forced(atom);
      }
      case NamedItemContext.PositiveLookahead λ_alt -> {
        var atom = visitAtom(λ_alt.atom);
        yield new Item.PositiveLookahead(atom);
      }
      case NamedItemContext.NegativeLookahead λ_alt -> {
        var atom = visitAtom(λ_alt.atom);
        yield new Item.NegativeLookahead(atom);
      }
      case NamedItemContext.Cut λ_alt -> {
        yield new Item.Cut();
      }
      case NamedItemContext.Eof λ_alt -> {
        yield new Item.EofMarker();
      }
    };
  }
  @Override
  public Item visitItem(ItemContext λ_ctx) {
    return switch (λ_ctx) {
      case ItemContext.Opt λ_alt -> {
        var atom = visitAtom(λ_alt.atom);
        yield new Item.Opt(atom);
      }
      case ItemContext.Repeat0 λ_alt -> {
        var atom = visitAtom(λ_alt.atom);
        yield new Item.Repeat0(atom);
      }
      case ItemContext.Repeat1 λ_alt -> {
        var atom = visitAtom(λ_alt.atom);
        yield new Item.Repeat1(atom);
      }
      case ItemContext.Gather λ_alt -> {
        var sep = visitAtom(λ_alt.sep);
        var node = visitAtom(λ_alt.node);
        yield new Item.Gather(node, sep);
      }
      case ItemContext.Atom λ_alt -> {
        var atom = visitAtom(λ_alt.atom);
        yield atom;
      }
    };
  }
  @Override
  public Item.Atom visitAtom(AtomContext λ_ctx) {
    return switch (λ_ctx) {
      case AtomContext.Name λ_alt -> {
        var NAME = λ_alt.NAME;
        yield new Item.NameLeaf(NAME);
      }
      case AtomContext.String λ_alt -> {
        var STRING = λ_alt.STRING;
        yield new Item.StringLeaf(STRING);
      }
    };
  }
}
