// generated by Pegen4J
package blue.heldplayer.pegen4j.peg;

import blue.heldplayer.pegen4j.peg.cst.*;

@SuppressWarnings("ALL")
public interface Pegen4JParserVisitor {
  default Object visitGrammarUnit(GrammarUnitContext ctx) { visitChildren(ctx); return null; }
  default Object visitGrammarElement(GrammarElementContext ctx) { visitChildren(ctx); return null; }
  default Object visitMeta(MetaContext ctx) { visitChildren(ctx); return null; }
  default Object visitToken(TokenContext ctx) { visitChildren(ctx); return null; }
  default Object visitRule(RuleContext ctx) { visitChildren(ctx); return null; }
  default Object visitRuleFlag(RuleFlagContext ctx) { visitChildren(ctx); return null; }
  default Object visitAlt(AltContext ctx) { visitChildren(ctx); return null; }
  default Object visitAction(ActionContext ctx) { visitChildren(ctx); return null; }
  default Object visitContextName(ContextNameContext ctx) { visitChildren(ctx); return null; }
  default Object visitNamedItem(NamedItemContext ctx) { visitChildren(ctx); return null; }
  default Object visitItem(ItemContext ctx) { visitChildren(ctx); return null; }
  default Object visitAtom(AtomContext ctx) { visitChildren(ctx); return null; }

  default Object visit(blue.heldplayer.pegen4j.parser.node.ParseNode node) {
    return switch (node) {
      case GrammarUnitContext c -> visitGrammarUnit(c);
      case GrammarElementContext c -> visitGrammarElement(c);
      case MetaContext c -> visitMeta(c);
      case TokenContext c -> visitToken(c);
      case RuleContext c -> visitRule(c);
      case RuleFlagContext c -> visitRuleFlag(c);
      case AltContext c -> visitAlt(c);
      case ActionContext c -> visitAction(c);
      case ContextNameContext c -> visitContextName(c);
      case NamedItemContext c -> visitNamedItem(c);
      case ItemContext c -> visitItem(c);
      case AtomContext c -> visitAtom(c);
      default -> null;
    };
  }

  default void visitChildren(blue.heldplayer.pegen4j.parser.node.RuleContext ctx) {
    for (blue.heldplayer.pegen4j.parser.node.ParseNode child : ctx.children()) {
      if (child instanceof blue.heldplayer.pegen4j.parser.node.RuleContext rc) {
        visit(rc);
      }
    }
  }
}
