// generated by Pegen4J
package blue.heldplayer.pegen4j.peg.cst;

import java.util.List;

@SuppressWarnings("ALL")
public final class AltContext extends blue.heldplayer.pegen4j.parser.node.RuleContext {
  public List<NamedItemContext> items;
  public ActionContext action;
  public ContextNameContext context_name;
}
