// generated by Pegen4J
package blue.heldplayer.pegen4j.peg.cst;

import java.util.List;

@SuppressWarnings("ALL")
public final class GrammarUnitContext extends blue.heldplayer.pegen4j.parser.node.RuleContext {
  public List<GrammarElementContext> grammar_elements;
}
