// generated by Pegen4J
package blue.heldplayer.pegen4j.peg.cst;

import blue.heldplayer.pegen4j.parser.node.PatternTokenNode;
import java.util.List;

@SuppressWarnings("ALL")
public sealed abstract class MetaContext extends blue.heldplayer.pegen4j.parser.node.RuleContext {

  public static final class Keyword extends MetaContext {
    public List<PatternTokenNode> keywords;
  }

  public static final class Ignore extends MetaContext {
    public List<PatternTokenNode> names;
  }

  public static final class Option extends MetaContext {
    public PatternTokenNode name;
    public List<PatternTokenNode> values;
  }

  public static final class Recover extends MetaContext {
    public List<PatternTokenNode> tokens;
  }
}
