// generated by Pegen4J
package blue.heldplayer.pegen4j.peg.cst;

import blue.heldplayer.pegen4j.parser.node.PatternTokenNode;
import java.util.List;

@SuppressWarnings("ALL")
public final class RuleContext extends blue.heldplayer.pegen4j.parser.node.RuleContext {
  public PatternTokenNode NAME;
  public PatternTokenNode TYPE;
  public List<RuleFlagContext> flags;
  public List<AltContext> alts;
}
