// generated by Pegen4J
package blue.heldplayer.pegen4j.peg.cst;

import blue.heldplayer.pegen4j.parser.node.PatternTokenNode;
import java.util.List;

@SuppressWarnings("ALL")
public sealed abstract class RuleContext extends blue.heldplayer.pegen4j.parser.node.RuleContext {

  public static final class Typed extends RuleContext {
    public PatternTokenNode NAME;
    public PatternTokenNode TYPE;
    public List<AltContext> alts;
  }

  public static final class Untyped extends RuleContext {
    public PatternTokenNode NAME;
    public List<AltContext> alts;
  }
}
