// generated by Pegen4J
import cst.*;

import blue.heldplayer.pegen4j.parser.node.BaseNode;
import blue.heldplayer.pegen4j.parser.node.PatternTokenNode;
import blue.heldplayer.pegen4j.parser.node.StringTokenNode;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@SuppressWarnings("ALL")
public class ImplicitTypeFromRuleAstBuilder implements ImplicitTypeFromRuleVisitor {
  @Override
  public SomeType visitRuleAtom(RuleAtomContext λ_ctx) {
    var typed_rule = visitTypedRule(λ_ctx.typed_rule);
    return typed_rule;
  }
  @Override
  public SomeType visitRuleOpt(RuleOptContext λ_ctx) {
    var typed_rule = Optional.ofNullable(λ_ctx.typed_rule).map(c -> visitTypedRule(c)).orElse(null);
    return typed_rule;
  }
  @Override
  public List<SomeType> visitRuleRepeat0(RuleRepeat0Context λ_ctx) {
    var typed_rule = λ_ctx.typed_rule.stream().map(c -> visitTypedRule(c)).collect(Collectors.toList());
    return typed_rule;
  }
  @Override
  public List<SomeType> visitRuleRepeat1(RuleRepeat1Context λ_ctx) {
    var typed_rule = λ_ctx.typed_rule.stream().map(c -> visitTypedRule(c)).collect(Collectors.toList());
    return typed_rule;
  }
  @Override
  public List<SomeType> visitRuleGather(RuleGatherContext λ_ctx) {
    var typed_rule = λ_ctx.typed_rule.stream().map(c -> visitTypedRule(c)).collect(Collectors.toList());
    return typed_rule;
  }
  @Override
  public SomeType visitTypedRule(TypedRuleContext λ_ctx) {
    return switch (λ_ctx) {
      case TypedRuleContext.Alt1 λ_alt -> {
        yield SomeType.FOO;
      }
      case TypedRuleContext.Alt2 λ_alt -> {
        yield SomeType.BAR;
      }
    };
  }
}