// generated by Pegen4J
import cst.*;

import blue.heldplayer.pegen4j.parser.AbstractParser;
import blue.heldplayer.pegen4j.parser.TokenType;
import blue.heldplayer.pegen4j.parser.node.PatternTokenNode;
import blue.heldplayer.pegen4j.parser.node.StringTokenNode;

import java.net.URI;
import java.util.ArrayList;

@SuppressWarnings("ALL")
public class UnreachableCode extends AbstractParser {

  public static final TokenType[] TOKENS = new TokenType[]{};
  public static final TokenType[] IGNORED_TOKENS = new TokenType[]{};
  public static final String[] KEYWORDS = new String[]{"FOOBAR"};
  public static final String[] SOFT_KEYWORDS = new String[]{};

  public UnreachableCode(URI sourceUri, CharSequence sourceString) {
    super(sourceUri, sourceString, TOKENS, IGNORED_TOKENS, KEYWORDS, SOFT_KEYWORDS);
  }

  public RuleOptContext rule_opt() {
    return super.memoized("rule_opt", () -> {
      var λ_mark = super.mark();
      // 'FOOBAR'?
      do {
        var λ_ctx = new RuleOptContext();
        var λv_e = super.expect("FOOBAR");
        if (λv_e != null) λ_ctx.add(λv_e);
        λ_ctx.e = λv_e;
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      // unreachable
    });
  }

  public RuleRepeat0Context rule_repeat0() {
    return super.memoized("rule_repeat0", () -> {
      var λ_mark = super.mark();
      // 'FOOBAR'*
      do {
        var λ_ctx = new RuleRepeat0Context();
        var λv_e = new ArrayList<StringTokenNode>();
        while (true) {
          var λ_m = super.mark();
          var λe_e = super.expect("FOOBAR");
          if (λe_e == null) { super.reset(λ_m); break; }
          λv_e.add(λe_e);
          λ_ctx.add(λe_e);
        }
        λ_ctx.e = λv_e;
        super.finish(λ_ctx, λ_mark);
        return λ_ctx;
      } while (false);
      // unreachable
    });
  }

}