// generated by Pegen4J
package blue.heldplayer.pegen4j.peg.cst;

import blue.heldplayer.pegen4j.parser.node.PatternTokenNode;

@SuppressWarnings("ALL")
public sealed abstract class AtomContext extends blue.heldplayer.pegen4j.parser.node.RuleContext {

  public static final class Name extends AtomContext {
    public PatternTokenNode NAME;
  }

  public static final class String extends AtomContext {
    public PatternTokenNode STRING;
  }
}
