// generated by Pegen4J
package blue.heldplayer.pegen4j.peg.cst;

@SuppressWarnings("ALL")
public sealed abstract class GrammarElementContext extends blue.heldplayer.pegen4j.parser.node.RuleContext {

  public static final class Alt1 extends GrammarElementContext {
    public MetaContext meta;
  }

  public static final class Alt2 extends GrammarElementContext {
    public TokenContext token;
  }

  public static final class Alt3 extends GrammarElementContext {
    public RuleContext rule;
  }
}
