// generated by Pegen4J
package blue.heldplayer.pegen4j.peg.cst;

@SuppressWarnings("ALL")
public sealed abstract class ItemContext extends blue.heldplayer.pegen4j.parser.node.RuleContext {

  public static final class Opt extends ItemContext {
    public AtomContext atom;
  }

  public static final class Repeat0 extends ItemContext {
    public AtomContext atom;
  }

  public static final class Repeat1 extends ItemContext {
    public AtomContext atom;
  }

  public static final class Gather extends ItemContext {
    public AtomContext sep;
    public AtomContext node;
  }

  public static final class Atom extends ItemContext {
    public AtomContext atom;
  }
}
