// generated by Pegen4J
package blue.heldplayer.pegen4j.peg.cst;

import blue.heldplayer.pegen4j.parser.node.PatternTokenNode;

@SuppressWarnings("ALL")
public sealed abstract class NamedItemContext extends blue.heldplayer.pegen4j.parser.node.RuleContext {

  public static final class Named extends NamedItemContext {
    public PatternTokenNode NAME;
    public ItemContext item;
  }

  public static final class Unnamed extends NamedItemContext {
    public ItemContext item;
  }

  public static final class Forced extends NamedItemContext {
    public AtomContext atom;
  }

  public static final class PositiveLookahead extends NamedItemContext {
    public AtomContext atom;
  }

  public static final class NegativeLookahead extends NamedItemContext {
    public AtomContext atom;
  }

  public static final class Cut extends NamedItemContext {
  }

  public static final class Eof extends NamedItemContext {
  }
}
