// generated by Pegen4J
package blue.heldplayer.pegen4j.peg.cst;

import blue.heldplayer.pegen4j.parser.node.PatternTokenNode;

@SuppressWarnings("ALL")
public final class TokenContext extends blue.heldplayer.pegen4j.parser.node.RuleContext {
  public PatternTokenNode NAME;
  public PatternTokenNode PATTERN;
}
